### ISSUE TITLE
allow weight field to take decimals

### ISSUE THREAD

**Issue by HarleyCarter1234** [aceberg/ExerciseDiary#4]
Weight field does not currently allow decimals and seems to expect a whole number

Change 'weight' field from int to single/double etc

Trying to enter 102.5 for example fails

**Comment by HarleyCarter1234** [comment]
should have maybe added that I'm in the UK and measuring weights in KG

**Comment by chandz05** [comment]
Would like this too please! Rounding up/down to the nearest whole number makes the graph fluctuate weirdly, even in freedom lbs.
