### ISSUE TITLE
[Feature Requests] Cardio and Sets

### ISSUE THREAD

**Issue by rwlove** [aceberg/ExerciseDiary#6]
This app is great! I request a few features.

1. Cardio
- duration
- other modifiers (treadmill speed, treadmill incline - for example)

2. Sets
- Allow for sets within an exercise with different reps/weights (I did two sets of curls, first one was 10x 40lbs, second one was 8x 35lbs - for example)

**Comment by bkinder83** [comment]
Another feature request would be to allow the user to input a workout program. Open up the day and it has the exercise/sets/weights ready waiting.
