### ISSUE TITLE
A demo site for ExerciseDiary

### ISSUE THREAD

**Issue by louislam** [aceberg/ExerciseDiary#7]
I recently dockerize my project Demo Kuma which can be used to provide a demo for your project to your users. 

I used your project as a showcase, I think you may be interested in.

ExerciseDiary Live Demo (2 mins):
https://exercisediary-demo.kuma.pet/start-demo

You can setup your own server if you are interested in.

My project: 
https://github.com/louislam/demo-kuma

Reddit post:
https://www.reddit.com/r/selfhosted/comments/191rrjf/demo_kuma_for_selfhosted_app_developers_to_create/

**Comment by aceberg** [comment]
That's cool! Screenshots are good, but demo is always better)

Will it be ok if I add a link to your demo in the README? Like this:

[**Demo**](https://exercisediary-demo.kuma.pet/start-demo) made by [louislam](https://github.com/louislam) with [demo-kuma](https://github.com/louislam/demo-kuma)
