### ISSUE TITLE
Mobile Responsive Design for heat map

### ISSUE THREAD

**Issue by mirx1** [aceberg/ExerciseDiary#9]
Heat map flows off the side of chrome on android, running on Samsung S22

![Screenshot_20240202_170827_Chrome](https://github.com/aceberg/ExerciseDiary/assets/5804553/1c3b02b3-471f-49d4-912d-eb75c78698e2)
![Screenshot_20240202_170842_Chrome](https://github.com/aceberg/ExerciseDiary/assets/5804553/17d2ec45-457d-415e-873c-de93ba2ec546)

**Comment by aceberg** [comment]
Finally, I figured out how to fix that!
